USE MASTER
GO

IF NOT EXISTS(SELECT name FROM master.dbo.sysdatabases WHERE name ='Sellers_DB')

CREATE DATABASE Sellers_DB

GO

USE Sellers_DB

GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'CITY')

CREATE TABLE CITY(
CODE INT PRIMARY KEY IDENTITY (1,1),
DESCRIPTION varchar(30) not null
)

GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'SELLER')

CREATE TABLE SELLER(
CODE INT PRIMARY KEY IDENTITY (1,1),
NAME varchar(50) not null,
LAST_NAME varchar(50) not null,
DOCUMENT varchar(20) not null,
CITY_ID INT not null
)

GO


ALTER TABLE SELLER
ADD CONSTRAINT FK_CITY_SELLER
FOREIGN KEY (CITY_ID) REFERENCES CITY(CODE)